### ISSUE TITLE
Stuck at red menu screen

### ISSUE THREAD

**Issue by LTGZZ** [thevoidnn/wine20-bcrypt-doom#1]
Hi !
Nice patch, and shame on Bethesda for not supporting Linux.
Followed your instructions on Slackware, I already have a working installation of Steam.

I have the intro, the music, but when switching to the red screen, the screen freezes.
I only can see "campaign" and listen to the music.

The final log lines :
err:ole:CoCreateInstanceEx apartment not initialised
err:ole:CoCreateInstanceEx apartment not initialised
err:ole:CoCreateInstanceEx apartment not initialised
err:ole:CoCreateInstanceEx apartment not initialised
err:ole:CoCreateInstanceEx apartment not initialised
err:ole:CoCreateInstanceEx apartment not initialised
err:ole:CoCreateInstanceEx apartment not initialised
err:ole:CoCreateInstanceEx apartment not initialised
err:ole:CoCreateInstanceEx apartment not initialised
err:ole:CoCreateInstanceEx apartment not initialised
err:ole:CoCreateInstanceEx apartment not initialised
err:ole:CoCreateInstanceEx apartment not initialised
err:ole:CoCreateInstanceEx apartment not initialised
err:ole:CoCreateInstanceEx apartment not initialised
err:ole:CoCreateInstanceEx apartment not initialised
err:ole:CoCreateInstanceEx apartment not initialised
err:ole:CoCreateInstanceEx apartment not initialised
err:ole:CoCreateInstanceEx apartment not initialised
err:ole:CoCreateInstanceEx apartment not initialised
err:ole:CoCreateInstanceEx apartment not initialised
err:ole:CoCreateInstanceEx apartment not initialised
err:ole:CoCreateInstanceEx apartment not initialised
err:ole:CoCreateInstanceEx apartment not initialised
err:ole:CoCreateInstanceEx apartment not initialised
err:ole:CoCreateInstanceEx apartment not initialised
err:ole:CoCreateInstanceEx apartment not initialised
err:ole:CoCreateInstanceEx apartment not initialised
err:ole:CoCreateInstanceEx apartment not initialised
err:ole:CoCreateInstanceEx apartment not initialised
fixme:bcrypt:Impl_BCryptCreateHash ignoring object buffer
fixme:bcrypt:Impl_BCryptCreateHash ignoring object buffer
fixme:bcrypt:BCryptGenerateSymmetricKey ignoring object buffer
fixme:bcrypt:key_init 128 bit key provided
fixme:bcrypt:Impl_BCryptCreateHash ignoring object buffer
fixme:bcrypt:Impl_BCryptCreateHash ignoring object buffer
fixme:bcrypt:BCryptGenerateSymmetricKey ignoring object buffer
fixme:bcrypt:key_init 128 bit key provided
fixme:bcrypt:Impl_BCryptCreateHash ignoring object buffer
fixme:bcrypt:Impl_BCryptCreateHash ignoring object buffer
fixme:bcrypt:BCryptGenerateSymmetricKey ignoring object buffer
fixme:bcrypt:key_init 128 bit key provided
fixme:bcrypt:Impl_BCryptCreateHash ignoring object buffer
fixme:bcrypt:Impl_BCryptCreateHash ignoring object buffer
fixme:bcrypt:BCryptGenerateSymmetricKey ignoring object buffer
fixme:bcrypt:key_init 128 bit key provided
fixme:bcrypt:Impl_BCryptCreateHash ignoring object buffer
fixme:bcrypt:Impl_BCryptCreateHash ignoring object buffer
fixme:bcrypt:BCryptGenerateSymmetricKey ignoring object buffer
fixme:bcrypt:key_init 128 bit key provided
fixme:bcrypt:Impl_BCryptCreateHash ignoring object buffer
fixme:bcrypt:Impl_BCryptCreateHash ignoring object buffer
fixme:bcrypt:BCryptGenerateSymmetricKey ignoring object buffer
fixme:bcrypt:key_init 128 bit key provided
fixme:bcrypt:Impl_BCryptCreateHash ignoring object buffer
fixme:bcrypt:Impl_BCryptCreateHash ignoring object buffer
fixme:bcrypt:BCryptGenerateSymmetricKey ignoring object buffer
fixme:bcrypt:key_init 128 bit key provided
fixme:bcrypt:Impl_BCryptCreateHash ignoring object buffer
fixme:bcrypt:Impl_BCryptCreateHash ignoring object buffer
fixme:bcrypt:BCryptGenerateSymmetricKey ignoring object buffer
fixme:bcrypt:key_init 128 bit key provided
fixme:bcrypt:Impl_BCryptCreateHash ignoring object buffer
fixme:bcrypt:Impl_BCryptCreateHash ignoring object buffer
fixme:bcrypt:BCryptGenerateSymmetricKey ignoring object buffer
fixme:bcrypt:key_init 128 bit key provided
fixme:bcrypt:Impl_BCryptCreateHash ignoring object buffer
fixme:bcrypt:Impl_BCryptCreateHash ignoring object buffer
fixme:bcrypt:BCryptGenerateSymmetricKey ignoring object buffer
fixme:bcrypt:key_init 128 bit key provided
fixme:bcrypt:Impl_BCryptCreateHash ignoring object buffer
fixme:bcrypt:Impl_BCryptCreateHash ignoring object buffer
fixme:bcrypt:BCryptGenerateSymmetricKey ignoring object buffer
fixme:bcrypt:key_init 128 bit key provided
err:ole:CoCreateInstanceEx apartment not initialised
err:ole:CoCreateInstanceEx apartment not initialised
err:ole:CoCreateInstanceEx apartment not initialised
err:ole:CoCreateInstanceEx apartment not initialised
err:ole:CoCreateInstanceEx apartment not initialised
err:ole:CoCreateInstanceEx apartment not initialised
err:ole:CoCreateInstanceEx apartment not initialised
err:ole:CoCreateInstanceEx apartment not initialised
err:ole:CoCreateInstanceEx apartment not initialised
err:ole:CoCreateInstanceEx apartment not initialised
err:ole:CoCreateInstanceEx apartment not initialised
err:ole:CoCreateInstanceEx apartment not initialised
err:ole:CoCreateInstanceEx apartment not initialised
err:ole:CoCreateInstanceEx apartment not initialised
err:ole:CoCreateInstanceEx apartment not initialised
err:ole:CoCreateInstanceEx apartment not initialised
fixme:thread:SetThreadIdealProcessor (0x4b4): stub
fixme:bcrypt:Impl_BCryptCreateHash ignoring object buffer
fixme:bcrypt:Impl_BCryptCreateHash ignoring object buffer
fixme:bcrypt:BCryptGenerateSymmetricKey ignoring object buffer
fixme:bcrypt:key_init 128 bit key provided
fixme:bcrypt:BCryptGenRandom ignoring selected algorithm
fixme:bcrypt:Impl_BCryptCreateHash ignoring object buffer
fixme:bcrypt:Impl_BCryptCreateHash ignoring object buffer
fixme:bcrypt:BCryptGenerateSymmetricKey ignoring object buffer
fixme:bcrypt:key_init 128 bit key provided
fixme:bcrypt:BCryptGenRandom ignoring selected algorithm
fixme:bcrypt:BCryptGenRandom ignoring selected algorithm
fixme:bcrypt:BCryptGenRandom ignoring selected algorithm
fixme:bcrypt:Impl_BCryptCreateHash ignoring object buffer
fixme:bcrypt:Impl_BCryptCreateHash ignoring object buffer
fixme:bcrypt:BCryptGenerateSymmetricKey ignoring object buffer
fixme:bcrypt:key_init 128 bit key provided
fixme:bcrypt:BCryptGenRandom ignoring selected algorithm
fixme:bcrypt:Impl_BCryptCreateHash ignoring object buffer
fixme:bcrypt:Impl_BCryptCreateHash ignoring object buffer
fixme:bcrypt:BCryptGenerateSymmetricKey ignoring object buffer
fixme:bcrypt:key_init 128 bit key provided
fixme:bcrypt:BCryptGenRandom ignoring selected algorithm
fixme:secur32:schannel_get_mac_algid unknown algorithm 200
fixme:bcrypt:Impl_BCryptCreateHash ignoring object buffer
fixme:bcrypt:Impl_BCryptCreateHash ignoring object buffer
fixme:bcrypt:BCryptGenerateSymmetricKey ignoring object buffer
fixme:bcrypt:key_init 128 bit key provided
fixme:system:SystemParametersInfoW Unknown action: 116

**Comment by LTGZZ** [comment]
Fixed it with the /etc/hosts entries.

**Comment by LTGZZ** [comment]
Played for an hour fullscreen without a problem.
Thanks again, I bought Doom 2016 since day one, and never played it since today !

**Comment by strycore** [comment]
@LTGZZ did you use the devMode_enable flag or have you managed to run without?

**Comment by LTGZZ** [comment]
Yes, I followed strictly the how to.
